name: cshl2024
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - ffmpeg
  - pytorch
  - pytorch-cuda=12.1
  - pip:
      - -r file:https://raw.githubusercontent.com/LabForComputationalVision/plenoptic-cshl-vision-2024/main/requirements.txt
